import './bootstrap';
import './auth.js';
import './theme.js';
import './users_filter.js';
import './pass_strength.js';
import './events.js';
import './mail_detail.js';
import './lecture_sidebar_filter.js';
import './lectures_filter.js';